/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/_workbench'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkbenchIndexRouteImport } from './routes/_workbench.index'
import { Route as WorkbenchChatRouteImport } from './routes/_workbench.chat'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as WorkbenchScriptsNameRouteImport } from './routes/_workbench.scripts.$name'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/_workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchIndexRoute = WorkbenchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchChatRoute = WorkbenchChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WorkbenchRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchScriptsNameRoute = WorkbenchScriptsNameRouteImport.update({
  id: '/scripts/$name',
  path: '/scripts/$name',
  getParentRoute: () => WorkbenchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkbenchIndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof WorkbenchChatRoute
  '/api/$': typeof ApiSplatRoute
  '/scripts/$name': typeof WorkbenchScriptsNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/chat': typeof WorkbenchChatRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof WorkbenchIndexRoute
  '/scripts/$name': typeof WorkbenchScriptsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workbench': typeof WorkbenchRouteWithChildren
  '/login': typeof LoginRoute
  '/_workbench/chat': typeof WorkbenchChatRoute
  '/api/$': typeof ApiSplatRoute
  '/_workbench/': typeof WorkbenchIndexRoute
  '/_workbench/scripts/$name': typeof WorkbenchScriptsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/chat' | '/api/$' | '/scripts/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/chat' | '/api/$' | '/' | '/scripts/$name'
  id:
    | '__root__'
    | '/_workbench'
    | '/login'
    | '/_workbench/chat'
    | '/api/$'
    | '/_workbench/'
    | '/_workbench/scripts/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkbenchRoute: typeof WorkbenchRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workbench': {
      id: '/_workbench'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workbench/': {
      id: '/_workbench/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchIndexRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_workbench/chat': {
      id: '/_workbench/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof WorkbenchChatRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workbench/scripts/$name': {
      id: '/_workbench/scripts/$name'
      path: '/scripts/$name'
      fullPath: '/scripts/$name'
      preLoaderRoute: typeof WorkbenchScriptsNameRouteImport
      parentRoute: typeof WorkbenchRoute
    }
  }
}

interface WorkbenchRouteChildren {
  WorkbenchChatRoute: typeof WorkbenchChatRoute
  WorkbenchIndexRoute: typeof WorkbenchIndexRoute
  WorkbenchScriptsNameRoute: typeof WorkbenchScriptsNameRoute
}

const WorkbenchRouteChildren: WorkbenchRouteChildren = {
  WorkbenchChatRoute: WorkbenchChatRoute,
  WorkbenchIndexRoute: WorkbenchIndexRoute,
  WorkbenchScriptsNameRoute: WorkbenchScriptsNameRoute,
}

const WorkbenchRouteWithChildren = WorkbenchRoute._addFileChildren(
  WorkbenchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkbenchRoute: WorkbenchRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
